# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: snadaras <snadaras@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/04/04 13:24:59 by snadaras          #+#    #+#              #
#    Updated: 2018/04/04 17:37:51 by snadaras         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = army
SOURCES = \
  people.ml \
  doctor.ml \
  dalek.ml \
  army.ml \
  main.ml
  
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
